### ISSUE TITLE
dist directory not present after initial setup

### ISSUE THREAD

**Issue by pigeonflight** [collective/collective.angularstarter#2]
The README does not document how to generate the 'dist' directory. This is required as the directory is used to register the ICollectiveAngularstarterProductionLayer Layer in the browser/configure.zcml
file.

In the absence of the 'dist' directory the zeo clients will not start and will return errors, such as:

```
 ConfigurationError: Directory   
  .../collective.angularstarter/collective/angularstarter/browser/angular/dist/++resource++collective.angularstarter.styles does not exist
```

**Comment by pigeonflight** [comment]
The solution to creating the 'dist' folder is to issue the command 

```
 grunt build
```

This will create the appropriate resources. This needs to be documented in the README as some persons are unfamiliar with the grunt/yeoman workflow.

**Comment by davidemoro** [comment]
Hi @pigeonflight,

I've missed the "grunt build" step in the README file. I think the whole README file should be improved as well.

**Comment by davidemoro** [comment]
Thank you @pigeonflight!

It should be closed now since I've added the "grunt build" step on readme.
